# Generated by Django 2.0.13 on 2019-05-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comments_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
